### ISSUE TITLE
Issues with restarting stream after it being automatically disconnected due to user leaving the app

### ISSUE THREAD

**Issue by lukkas** [Streamaxia/iOS-Open-SDK#15]
When user is streaming and leaves the app, the stream disconnects - this is expected. But when the app returns to foreground and startStreaming is called again, oftentimes some issues occur. We've observed 3 different ones.
1. We're getting `Calling too stop/start too fast. Dropping calls`
2. Start streaming doesn't call the completion block, but the stream actually starts streaming. When this happens, `recorder(_ :didUpdateStreamTime:)` isn't getting called during stream.
3. `keychainAccessFailure` error is reported. When this happens, stream status changes to `recording`, `recorder(_ :didUpdateStreamTime:)` is getting called as if the stream worked correctly, however no stream data is being received by the server - when testing on youtube, it shows `OFFLINE` status.

**Comment by mihaimotocu** [comment]
Hi! Please use the support system to connect with us. Thank you!
