### ISSUE TITLE
Crashing with AURemoteIO::IOThread (9): EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by lukkas** [Streamaxia/iOS-Open-SDK#9]
When I stream over stream over my local network using this little tool
https://github.com/sallar/mac-local-rtmp-server
test app keeps crashing with this message:
`AURemoteIO::IOThread (9): EXC_BAD_ACCESS`
I'm also getting `0 AdvancePsyOut` at the end of my stack trace. Unfortunately there's no more information to it.

Sometimes it happens after several seconds, sometimes after few minutes, but If I keep the stream for long enough it always happens for me.

Device: iPhone 11 Pro
iOS version: 13.4

**Comment by chelemen-razvan** [comment]
Fixed in 13f10d0b0e928c285bdd47ed42b549849fe82f2e

**Comment by lukkas** [comment]
It doesn't crash anymore. Thank you!
